server:
  port: 8080
spring:
  profiles:
    active: ${build.profile.id}
  application:
    name: dili-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://uap.diligrp.com"
            allowedMethods:
              - GET
              - POST
      discovery:
        locator:
          enabled: true
          # 服务名小写
          lower-case-service-id: true
#      routes:
#      - id: customer-service-proxy
#        uri: lb://customer-service
##        uri: http://localhost:8181
#        predicates:
#        - Path=/api/**
    nacos:
      discovery:
        enabled: true
        server-addr: 10.28.12.131:8848
        group: MICROSERVICE
        namespace: 54c39cfe-d1c4-4022-a94b-a3486c5927fc
        service: dili-gateway



logging:
  config: classpath:conf/logback-springboot.xml
management:
  metrics:
    export:
      dynatrace:
        device-id:
